apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 20.67.190.237
  selector:
    app: backend
